package com.tianxing.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.tianxing.common.model.base.BaseFilter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Filter extends BaseFilter<Filter> {
	public static final Filter dao = new Filter();
	
	public Page<Filter> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from filter order by filterId asc");
	}
	
}
